plugins:
  pavilion_home_site_title:
    client: true
    default: "Hey, We're Pavilion."
  pavilion_home_site_description:
    client: true
    default: "We help people build online communities."
  pavilion_home_cta:
    client: true
    default: "Get in touch"
  pavilion_team_group:
    type: group
    default: "members"
    client: true
  pavilion_unassigned_tags:
    type: tag_list
    default: "dev-needed"
    client: true
  pavilion_plugin_assignments:
    type: list
    default: ""
  pavilion_plugin_assignment_categories:
    type: category_list
    default: ""
  max_earnings_target_month:
    default: 5000
  max_actual_hours_target_month:
    default: 240